format = """
$username\
$directory\
$vcsh\
$nix_shell\
$shell\
$shlvl\
$hostname\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$kubernetes\
$docker_context\
$package\
$conda\
$cmake\
$crystal\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$aws\
$gcloud\
$openstack\
$env_var\
$custom\
$cmd_duration\
$jobs\
$memory_usage\
$battery\
$time\
$status\
$line_break\
$character"""

# scan_timeout = 1000
# command_timeout = 10000

add_newline = true

[aws]
symbol = "â˜ï¸  ï‰° "
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "dimmed yellow"


[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "â˜ ï¸ "

[[battery.display]]
threshold = 10
style = "red"

[[battery.display]]
threshold = 30
style = "yellow"
discharging_symbol = "âš ï¸ "

[character]
success_symbol = "[Î» âœ](bold green)"
error_symbol = "[âˆ… âœ—](bold red)"
vicmd_symbol = "[îŸ… âœ](bold green) "

[cmake]
style = "blue"

[cmd_duration]
min_time = 500
style = "yellow"

[conda]
style = "green"

[crystal]
style = "red"

[dart]
style = "blue"

[deno]
style = "green"

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"
style = "cyan"

[docker_context]
style = "blue"

[dotnet]
symbol = "ğŸ¥… "
style = "blue"

[elixir]
style = "purple"

[elm]
style = "cyan"

[env_var]
variable = 'HOST'
default = "ğŸ‘‘"
style = "dimmed white"

[erlang]
style = "red"

[gcloud]
symbol = "â˜ï¸ ğŸ‡¬ï¸ "
style = "dimmed blue"

[git_branch]
symbol = "ğŸŒ± "
style = "purple"

[git_commit]
tag_symbol = "ğŸ”– "
style = "green"

[git_state]
format = '[\( $state ($progress_current of $progress_total)\)]($style) '
style = "dimmed red"
rebase = "REBASING ğŸ• "
merge = "MERGING ğŸ¦“ "
revert = "REVERTING ğŸ”™ "
cherry_pick = "CHERRY-PICKING ğŸ’ "
bisect = "BISECTING ğŸª "
am = "AM âœ‰ï¸ "
am_or_rebase = "AM/REBASE ğŸ• âœ‰ï¸ "

[git_status]
format = '([\[ $all_status$ahead_behind\]]($style) )'
style = "purple"
conflicted = "ğŸ”® "
ahead = "ğŸ ğŸ’¨"
behind = "ğŸ‘¾ "
diverged = "ğŸ¥¨ "
untracked = "ğŸš§ "
stashed = "ğŸ’­ "
modified = "âœ¨ "
staged = "ğŸ“¦ "
renamed = "ğŸ“› "
deleted = "ğŸ—‘ "

[golang]
style = "cyan"

[helm]
style = "white"

[hostname]
ssh_only = true
style = "dimmed green"
format = "on [$hostname]($style) "

[java]
style = "dimmed red"

[jobs]
style = "blue"

[julia]
style = "purple"

[kotlin]
style = "blue"

[kubernetes]
disabled = false
symbol = "â›µ "
format = 'on [$symbol$context \($namespace\)]($style) '
style = "cyan"

[line_break]
disabled = false

[lua]
style = "blue"

[memory_usage]
disabled = false
style = "dimmed white"

[hg_branch]
symbol = "ğŸ§ª "
style = "purple"

[nim]
style = "yellow"

[nix_shell]
style = "blue"

[nodejs]
style = "green"
not_capable_style = "red"

[ocaml]
style = "yellow"

[openstack]
symbol = "â˜ï¸ ğŸ…¾ "
style = "dimmed yellow"

[package]
symbol = "ğŸ "
style = "208"

[perl]
style = "149"

[php]
style = "147"

[purescript]
style = "white"

[python]
style = "yellow"

[rlang]
style = "blue"

[red]
style = "red"

[ruby]
style = "red"

[rust]
style = "red"

[scala]
style = "dimmed red"

[shell]
format = "$indicator "
disabled = false
bash_indicator = "ğ—¯ğ—®ğ˜€ğ—µ"
fish_indicator = "ğŸ "
zsh_indicator = "ğ˜‡ğ˜€ğ—µ"
powershell_indicator = "ï‘ _"
ion_indicator = "ğ—¶ğ—¼ğ—»"
elvish_indicator = "ğ—²ğ—¹ğ˜ƒğ—¶ğ˜€ğ—µ"
tcsh_indicator = "ğ˜ğ—°ğ˜€ğ—µ"
unknown_indicator = "â”"

[shlvl]
disabled = false
symbol = "â™»ï¸ "
format = "[$symbol $shlvl]($style) "
style = "yellow"
threshold = 2

[singularity]
style = "dimmed blue"

[status]
style = "red"
symbol = "ğŸš’"
signal_symbol = "âš¡ï¸"
format = '[ \[ $symbol $common_meaning$signal_name$maybe_int \]]($style) '
map_symbol = true
disabled = false

[swift]
style = "202"

[terraform]
style = "105"

[time]
disabled = false
format = 'at ğŸ•™ [$time]($style)'
style = "dimmed blue"
time_format = "%F %T %:z"

[username]
style_user = "dimmed blue"
style_root = "dimmed white"
disabled = false
show_always = true

[vagrant]
style = "cyan"

[vlang]
style = "blue"

[vcsh]
symbol = "ğŸ†…"
format = "[ $symbol $repo ]($style) "
style = "yellow"

[zig]
style = "yellow"

[custom.none]
style = "green"
